config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

resources :pages do
  member do
    put '/like' => 'pages#like'
    put '/dislike' => 'pages#dislike'
    get '/undislike' => 'pages#undislike'
    put '/unlike' => 'pages#unlike'
  end
end

  resources :users

    resources :reviews do
      resources :restaurants
    end

    resources :restaurants

  resources :restaurants do
    resources :reviews
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  # super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    # @review.find(:review_id)
    @user = User.find(params[:id])
    @review = @user.reviews
    if current_user != @user
      redirect_to "/"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
 <div id="alert-display"> </div>

<div class="container ">
  <div class="row">
    <% @review.each do |restaurant_review| %>

    <div class="col-md-6 ">
      <%= form_for restaurant_review,:html => {:class => "review-form-reviews", :id => "edit-review-form" }, remote: true do |t| %>

      <img style="margin-bottom: 15px; width:100%;" class="image-post" src="<%=restaurant_review.restaurant.picture %>" alt="#">
      <h4><b><%= restaurant_review.restaurant.name %></b></h4>
      <p ><%= t.text_field :title%></p>
      <%= t.select :role, [['Server'],['Bartender'],['Other']], :required => true, :prompt => "choose position" %><br>
      <%= t.number_field :tip_avg, placeholder: "Tip average/Hr", :required => true %><br>
      <h4>Clientele:</h4>

      <div class="container star-content">

        <%= t.radio_button :clientele,5, :id=> "5", :class => "star"  %><label id="clientele5" class="star" for="star5" title="Excellent!"></label><br>
        <%= t.radio_button :clientele, 4, :id=> "4", :class => "star"  %><label id="clientele4" class="star" for="star4" title="Good!"></label>
        <%= t.radio_button :clientele, 3, :id=> "3", :class => "star"  %><label id="clientele3" class="star" for="star3" title="Average!"></label>
        <%= t.radio_button :clientele, 2, :id=> "2", :class => "star"  %><label id="clientele2" class="star"  for="star2" title="Poor!"> </label>
        <%= t.radio_button :clientele, 1, :id => "1", :class => "star"   %><label id="clientele1" class="star"  for="star1" title=" very Poor!"> </label>
      </div>


      <h4>Team:</h4>

      <div class="container star-content">

        <%= t.radio_button :team, 5, :id =>  "t5", :class => "star-2" %><label id="team5" class="star-2" for="star5" title="Excellent!"></label><br>
        <%= t.radio_button :team, 4, :id =>  "t4", :class => "star-2" %><label id="team4" class="star-2" for="star4" title="Good!"> </label>
        <%= t.radio_button :team, 3, :id =>  "t3", :class => "star-2" %><label id="team3" class="star-2" for="star3" title="average!"> </label>
        <%= t.radio_button :team, 2, :id =>  "t2", :class => "star-2" %><label id="team2" class="star-2" for="star2" title="Poor!"> </label>
        <%= t.radio_button :team, 1, :id =>  "t1", :class => "star-2" %><label id="team1" class="star-2" for="star1" title=" very Poor!"> </label>

      </div>




      <h4>Management:</h4>
      <div class="container star-content">


        <%= t.radio_button :management, 5, :id => "m5", :class => "star-3"  %><label id="mange5" class="star-3" for="star5" title="Excellent!"> </label><br>
        <%= t.radio_button :management, 4, :id => "m4", :class => "star-3"  %><label id="mange4" class="star-3" for="star5" title="Good!"> </label>
        <%= t.radio_button :management, 3, :id => "m3", :class => "star-3"  %><label id="mange3" class="star-3" for="star5" title="Average!"></label>
        <%= t.radio_button :management, 2, :id => "m2", :class => "star-3"  %><label id="mange2" class="star-3" for="star5" title="Poor!"></label>

        <%= t.radio_button :management, 1, :id =>  "m1", :class => "star-3"  %><label id="mange1" class="star-3" for="star5" title="Very Poor!"> </label>
      </div>

      <h4>Rating:</h4>

      <div class="container star-content">

        <%= t.radio_button :rating,5, :id =>"r5", :class => "star-4" %><label id="rate5" class="star-4" for="star5" title="Excellent!"> </label>
        <%= t.radio_button :rating,4, :id =>"r4", :class => "star-4" %><label id="rate4" class="star-4" for="star5" title="Good!"> </label>
        <%= t.radio_button :rating,3, :id =>"r3", :class => "star-4" %><label id="rate3" class="star-4" for="star5" title="Average!"> </label>
        <%= t.radio_button :rating,2, :id =>"r2", :class => "star-4" %><label id="rate2" class="star-4" for="star5" title="Poor!"> </label>
        <%= t.radio_button :rating,1, :id =>"r1", :class => "star-4" %><label id="rate1" class="star-4" for="star5" title="Very Poor!"> </label><br/>
      </div>



      <%= t.rich_text_area :content, placeholder: "Add Details", class: "trix-editor-reviews" %><br/>

      <%= t.submit "Update Review", data: {disable_with: "Submitting..."}, class: "btn btn-success update-button-reviews" %><br>

      <%= link_to "Delete Review", review_path(restaurant_review),  method: :delete, remote: true, data: {confirm: "Are Your Sure you want to delete this review?"}, class: "btn btn-danger" %>

      <% end %>
    </div>
    <% end %>
  </div>
</div>

<script>
  setTimeout(function(){ starSelection();}, 2000);

    console.log("i'm loaded!")

   function starSelection(){



  let clientele = document.getElementsByClassName("star");

   for (const c  of clientele){
    c.addEventListener('click', function(){
      c.previousSibling.checked = true
    })
   };

   let team = document.getElementsByClassName("star-2");

   for (const t  of team){
    t.addEventListener('click', function(){
      t.previousSibling.checked = true
    })
   };

   let management = document.getElementsByClassName("star-3");

   for (const m  of management){
    m.addEventListener('click', function(){
      m.previousSibling.checked = true
    })
   };

   let rating = document.getElementsByClassName("star-4");

   for (const r  of rating){
    r.addEventListener('click', function(){
      r.previousSibling.checked = true
    })
   };

 };

</script>