config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

resources :pages do
  member do
    put '/like' => 'pages#like'
    put '/dislike' => 'pages#dislike'
    get '/undislike' => 'pages#undislike'
    put '/unlike' => 'pages#unlike'
  end
end

  resources :users

    resources :reviews do
      resources :restaurants
    end

    resources :restaurants

  resources :restaurants do
    resources :reviews
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tips</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
  <nav>
    <div class="navbar">
      <ul>
        <li><img class="star-logo" src="/star.png" alt="#"></li>
        <li class="logo">Tips</li>

        <li><%= link_to "Reviews", root_path %></li>

        <li><%= link_to "Restaurant search", restaurants_path if user_signed_in? %></li>
        <% if user_signed_in? %>
        <li><%=link_to "log-out", destroy_user_session_path, method: :delete %></li>

        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
      <% if user_signed_in? %>
    <li class="dropdown user-dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><%= current_user.email if user_signed_in? %>
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
    <li><%= link_to "Account", user_path(current_user) %></li>
    <li><%= link_to "Cancel Account", edit_user_registration_path %></li>
  </ul>
        </li>
        <% end %>
  </nav>


  <div class="container">
    <% if notice %><div  class="alert alert-info alert-display"> <%= notice %></div> <% end %>
    <% if alert %><div  class="alert alert-warning alert-display"><%= alert %></div> <% end %>
  </div>


  <%= yield %>

</body>

<script>

$(".alert-info").fadeOut(5000);




</script>
</html>